### ISSUE TITLE
Fix scaling for pixel-perfect emotes

### ISSUE THREAD

**Issue by noodlebox** [noodlebox/KawaiiDiscord#11]
Most Twitch and BTTV emotes are 28x28, or slightly smaller. Scaling them up to 32x32 in Discord (when `.jumboable`) is ugly. This CSS improves their appearance:
```css
.emoji {
    object-fit: scale-down;
}
```
This doesn't work well if the user also has custom styling to make emotes larger, using `width` and `height`. `zoom` works well instead, and will also benefit from high-DPI versions when available (#10), though it currently causes tooltips to appear in the wrong place. `image-rendering: pixelated` ensures pixel-perfect emotes are scaled up without making them a blurry mess.
```css
.emoji.jumboable {
    object-fit: scale-down;
    zoom: 200%;
    image-rendering: pixelated;
}
```
Using their native sizes is an option, but will require knowing their dimensions ahead of time (provided by most of the APIs), or else suffer reflows every time an emote loads.

- [ ] Add basic CSS, encourage use of `zoom` for users wanting giant emotes.
- [ ] Fix tooltip position for zoomed-in elements.
- [ ] Add settings panel options for larger emote sizes.
